[workspace]
resolver = "2"
members = ["cached", "cached-server", "cached-client"]

[workspace.dependencies]
tokio = { version = "1.25.0" }
clap = { version = "4.1.6" }
tracing = { version = "0.1" }
nom = { version = "7.1" }