name: General checks and tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check_test:
    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@just
      
    - name: Run check
      run: make check
      
    - name: Run tests
      run: make test
