name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run check
      run: make check
      
    - name: Run tests
      run: make test
